/**
 * Website Build Spec - Generated by GPT
 * This is the intermediate representation of the website structure
 */
export interface WebsiteBuildSpec {
  spec_version: string;
  tenant: {
    business_name: string;
    legal_name: string;
    industry: string;
    tagline: string;
    tone_of_voice: string;
    usp_bullets: string[];
    avoid_claims_or_words: string[];
  };
  branding: {
    logo_url: string;
    primary_colour_hex: string;
    secondary_colour_hex: string;
    design_vibe: string;
  };
  contact: {
    phone: string;
    email: string;
    address: string;
    opening_hours: string;
    cta_primary: string;
    cta_secondary: string;
  };
  service_area: {
    mode: "radius" | "list" | "nationwide";
    radius_miles: number;
    areas: string[];
    primary_location: string;
  };
  seo_defaults: {
    locale: string;
    brand_name: string;
    primary_location: string;
    service_area_hint: string;
  };
  navigation: {
    header_links: NavLink[];
    footer_links: NavLink[];
  };
  pages: SpecPage[];
  global_blocks: {
    footer: {
      disclaimer: string;
      copyright_text: string;
    };
  };
  assets: {
    image_style_notes: string;
    image_requests: ImageRequest[];
  };
  change_policy_hints: {
    self_serve: string[];
    managed_changes: string[];
  };
}

export interface NavLink {
  label: string;
  href: string;
}

export interface SpecPage {
  id: string;
  title: string;
  slug: string;
  purpose: string;
  seo: {
    title: string;
    meta_description: string;
    primary_keyword: string;
    secondary_keywords: string[];
    og_title?: string;
    og_description?: string;
  };
  sections: SpecSection[];
}

export interface SpecSection {
  type: BlockType;
  props: Record<string, unknown>;
}

export interface ImageRequest {
  section_ref: string;
  description: string;
  keywords: string[];
}

/**
 * CMS Seed - Generated by Claude
 * This is imported directly into the database
 */
export interface CMSSeed {
  settings: SiteSettings;
  navigation: NavigationConfig;
  pages: SeedPage[];
}

export interface SiteSettings {
  siteName: string;
  tagline: string;
  contact: {
    phone: string;
    email: string;
    address: string;
    openingHours: string;
  };
  colours: {
    primary: string;
    secondary: string;
  };
  footer: {
    disclaimer: string;
    copyrightText: string;
  };
}

export interface NavigationConfig {
  headerLinks: NavLink[];
  footerLinks: NavLink[];
}

export interface SeedPage {
  title: string;
  slug: string;
  seoTitle: string;
  seoDescription: string;
  blocks: SeedBlock[];
}

export interface SeedBlock {
  blockType: BlockType;
  data: Record<string, unknown>;
}

/**
 * Allowed block types
 */
export type BlockType =
  | "hero"
  | "services_grid"
  | "about_split"
  | "testimonial_list"
  | "accreditations_row"
  | "gallery_grid"
  | "faq_accordion"
  | "service_area"
  | "contact_form"
  | "cta_banner"
  | "rich_text";

export const ALLOWED_BLOCK_TYPES: BlockType[] = [
  "hero",
  "services_grid",
  "about_split",
  "testimonial_list",
  "accreditations_row",
  "gallery_grid",
  "faq_accordion",
  "service_area",
  "contact_form",
  "cta_banner",
  "rich_text",
];

/**
 * Plan configuration
 */
export const PLAN_PAGE_COUNTS = {
  1: 1,
  5: 5,
  10: 10,
} as const;

export type PlanPages = keyof typeof PLAN_PAGE_COUNTS;
